name: Update Team Points

on:
  workflow_run:
    workflows: ["Validate Multi-language Solutions"]
    types:
      - completed

jobs:
  update-points:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Download points artifact from upstream workflow
        uses: actions/download-artifact@v4
        with:
          name: points-file
          run-id: ${{ github.event.workflow_run.id }}
          path: .

      - name: Read points, challenge name, and author from file
        id: read-points
        run: |
          if [ -f .points ]; then
            source .points
          else
            echo "No .points file found; setting defaults."
            CHALLENGE_NAME="Unknown"
            POINTS=0
            AUTHOR="Unknown"
          fi
          DATE=$(date +'%Y-%m-%d %H:%M:%S')
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "POINTS=$POINTS" >> $GITHUB_ENV
          echo "CHALLENGE_NAME=$CHALLENGE_NAME" >> $GITHUB_ENV

      - name: Append to team_points.md
        run: |
          {
            echo "### $AUTHOR - $DATE"
            echo "| **Challenge** | **$CHALLENGE_NAME** |"
            echo "| **Total Points** | **$POINTS** |"
            echo ""
          } >> team_points.md

      - name: Commit team points update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add team_points.md
          git commit -m "Update team points for $AUTHOR (POINTS=$POINTS)" || echo "No changes to commit"
          git push || echo "Nothing to push"

      - name: Clean up points file
        run: |
          if [ -f .points ]; then
            rm .points
          else
            echo "No .points file to remove"
          fi
