name: Update Team Points

on:
  push:
    branches:
      - main
    paths:
      - "problems/**"

jobs:
  update-points:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Read points from file
        id: read-points
        run: |
          if [ -f .points ]; then
            POINTS=$(cat .points)
          else
            POINTS=0
          fi
          AUTHOR=$(git log -1 --pretty=format:'%an')
          DATE=$(date +'%Y-%m-%d %H:%M:%S')
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "POINTS=$POINTS" >> $GITHUB_ENV
      
      - name: Append to team_points.md
        run: |
          {
            echo "### $AUTHOR - $DATE"
            echo "| **Total Points** | **$POINTS** |"
            echo ""
          } >> team_points.md
      
      - name: Commit team points update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add team_points.md
          git commit -m "Update team points for $AUTHOR (POINTS=$POINTS)" || echo "No changes to commit"
          git push || echo "Nothing to push"

      - name: Clean up points file
        run: |
          if [ -f .points ]; then
            git rm .points
            git commit -m "Remove .points file after processing" || echo "No changes to commit"
            git push || echo "Nothing to push"
          else
            echo "No .points file to remove"
          fi
